# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

builds:  
  - id: dummy
    skip: true

dockers_v2:
  - id: standard
    images:
      - "ghcr.io/srlmgr/{{ .ProjectName }}"

    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://{{ .ModulePath }}"
      org.opencontainers.image.url: "https://{{ .ModulePath }}"

      org.opencontainers.image.description: "Admin Frontend for SimRacing League Manager"
      org.opencontainers.image.licenses: "GPL v3.0"
      description: "Admin Frontend for SimRacing League Manager"
      maintainer: "srlmgr"
    annotations:
      "index:org.opencontainers.image.description": "Admin Frontend for SimRacing League Manager"
    platforms:
      - linux/amd64
    sbom: true
    dockerfile: Dockerfile
    extra_files:
      - nginx.conf
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
    build_args:
      VITE_APP_VERSION: "{{ .Tag }}"
      VITE_GIT_SHA: "{{ .FullCommit }}"
      VITE_BUILD_DATE: "{{ .Date }}"
        
sboms:
  - artifacts: archive

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"


# signs our docker image
# https://goreleaser.com/customization/docker_sign
docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - "--yes"

# changelog will be generated by release-drafter now

release:
  prerelease: auto
  footer: |
    ---
    _Released with [GoReleaser](https://goreleaser.com)!_
